# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_orig', models.CharField(max_length=255)),
                ('title_rus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_orig', models.CharField(max_length=255)),
                ('title_rus', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('url', models.CharField(max_length=255, unique=True)),
                ('phase1', models.NullBooleanField()),
                ('phase2', models.NullBooleanField()),
                ('phase3', models.NullBooleanField()),
                ('phase4', models.NullBooleanField()),
                ('phase5', models.NullBooleanField()),
                ('phase6', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='activecomponent',
            name='raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimental.Raw'),
        ),
        migrations.AlterUniqueTogether(
            name='activecomponent',
            unique_together=set([('raw', 'title_orig')]),
        ),
    ]
