# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='active_components',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='raw',
            name='atc_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raw',
            name='phase1',
            field=models.NullBooleanField(help_text=b'for active components gathering'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='phase2',
            field=models.NullBooleanField(help_text=b'for atc code gathering'),
        ),
    ]
