# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimental', '0002_auto_20160129_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='alf_en',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='raw',
            name='alf_ru',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='raw',
            name='phase2',
            field=models.NullBooleanField(help_text=b'for active components gathering'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='phase3',
            field=models.NullBooleanField(help_text=b'for atc code gathering'),
        ),
    ]
