# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:48
from __future__ import unicode_literals

from django.db import migrations


def get_alf(apps, schema_editor):

    Raw = apps.get_model("experimental", "Raw")
    for raw in Raw.objects.all():
        raw.alf_en = raw.title_orig[:2]
        raw.alf_ru = raw.title_rus[:2]
        raw.save()


class Migration(migrations.Migration):

    dependencies = [
        ('experimental', '0003_auto_20160225_1947'),
    ]

    operations = [
        migrations.RunPython(get_alf)
    ]
